services:
  node:
    build:
      context: docker/node/
    working_dir: /application
    volumes:
      - .:/application
    command: sh -lc "npm ci && npm run watch"
    tty: true

  webserver:
    build:
      context: docker/nginx/
    depends_on:
      - php-fpm
    working_dir: /application
    volumes:
      - .:/application

  php-fpm:
    build:
      context: docker/php-fpm/
    working_dir: /application
    volumes:
      - .:/application
